FROM mcr.microsoft.com/devcontainers/base:noble

RUN apt-get update && apt-get install -y \
    vim \
    git \
    build-essential \
    curl \
    ca-certificates \
    pkg-config \
    && apt-get clean


